# Generated by Django 4.1 on 2022-09-23 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerystoreapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
