# Generated by Django 4.1 on 2022-10-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerystoreapp', '0002_orderdetail_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='numb_phone',
            field=models.IntegerField(default=None),
        ),
    ]
