# Generated by Django 4.1 on 2022-10-24 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocerystoreapp', '0003_order_address_order_numb_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='numb_phone',
        ),
    ]
