# Generated by Django 4.1 on 2022-10-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerystoreapp', '0004_remove_order_address_remove_order_numb_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
