# Generated by Django 4.1 on 2022-10-26 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerystoreapp', '0005_order_address_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
